# try:
#     print(x)
# except:
#     print("an error occured")

# try:
#     x=6
#     print(x)
# except:
#     print("error")
# else:
#     print("there is no error")
# finally:
#     print("program completed successfully")

# try:
#     print(x)
# except NameError:
#     print("variable is not defined")
# except:
#     print("error")

# x=int(input("enter a positive number"))
# if x<0:
#     raise Exception("negative numbers are not allowed")
# else:
#     print(x)